url: "https://buditanrim.co" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Budi Tanrim # the name of your site, e.g. ACME Corp.

# SEO
author: Budi Tanrim
twitter:
  username: buditanrim
  card: summary_large_image